# ---- AS5600 旋钮(只发滚动)----
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_INPUT_AMS_AS5600=y
# 调磁铁距离时:改成 y 且把 build.yaml 的 snippet 临时换回 zmk-usb-logging
CONFIG_ZMK_INPUT_AMS_AS5600_LOG_AGC=n

# ---- WS2812B 状态灯 ----
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_SPI=y
CONFIG_ZMK_RGB_ON_START=n

# ---- ZMK Studio 在线改键 ----
CONFIG_ZMK_STUDIO=y
# 免去物理解锁键(若你的 ZMK 版本没有此符号,删掉此行即可,只是会有一条警告)
CONFIG_ZMK_STUDIO_LOCKING=n
